#old_sound_rabbit_mq:
#    connections:
#        default:
#            url: '%env(RABBITMQ_URL)%'
#    producers:
#        # use 'old_sound_rabbit_mq.task_producer' service to send data.
#        task:
#            connection:       default
#            exchange_options: { name: 'task', type: direct }
#    consumers:
#        task:
#            connection:       default
#            exchange_options: { name: 'task', type: direct }
#            queue_options:    { name: 'task'}
#            callback:         App\Consumer\TaskConsumer

qubit_mq:
    sandbox: true
    producer:
        module: 'SKELETON' # nombre de modulo, va a ser univoco por la aplicacion que use el bundle
    consumers:
        skeleton: # nombre del consumer
            name: 'Skeleton' #'cola que va a rexibir mensajes' #UNA SOLA
            handler:
                - {name: SKELETON.COMPONENT.ACTION, service: App\Events\Handler\SkeletonMessageHandler}
#                - {name: sas.login.billing, service: servicio_billing}
#        billing:
#            name: 'job'
#            handler:
#                - {name: billing.job.biller, service: servicio_billing_biller}
#                - {name: billing.job.*, service: servicio_billing_job_rest}
#                - {name: billing.#, service: servicio_billing_rest}
